name: flutter_map
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  bloc_concurrency: ^0.2.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  hydrated_bloc: ^8.1.0
  flutter_staggered_grid_view: ^0.6.2
  freezed_annotation: ^2.1.0
  geocoding: ^2.0.5
  geolocator: ^9.0.1
  get_it: ^7.2.0
  google_maps_flutter: ^2.2.1
  http: ^0.13.4
  injectable: ^1.5.3
  json_annotation: ^4.6.0
  rxdart: ^0.27.5
  scroll_to_index: ^3.0.1
  sliding_up_panel: ^2.0.0+1
  uuid: ^3.0.6
  get: ^4.6.5
  connectivity_plus: ^2.3.7
  go_router: ^5.0.0
  sliding_sheet: ^0.5.2
  flutter_custom_clippers: ^2.0.0
  url_launcher: ^6.1.6
  intl: ^0.17.0

dev_dependencies:
  build_runner: ^2.1.11

  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

  freezed: ^2.1.0+1
  json_serializable: ^6.2.0

flutter:

  uses-material-design: true

  assets:
    - assets/ 
    - assets/images/
    - assets/images/products/
    - assets/images/partners/
    
